name: Deploy pharmacy backend to dev server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]



jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/pharmacy-backend
            git stash && git pull
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm i --legacy-peer-deps
            npm run build
            pm2 restart pharmacy-backend || pm2 start dist/index.js --name "pharmacy-backend"
